[Feature] Interface client responsive
CETEN-OpenBar/bar pull request #101
Opened 2024-09-15 10:59 UTC by aripot007

Ajoute une interface client responsive permettant de commander en ligne facilement depuis un autre appareil que les bornes. Les commandes faites en ligne sont distinguées des autres sur le comptoir par une icone, et peuvent être masquées.

- Ajoute les deux pages `/client/commande` et `/client/index`, qui sont des copies de `/borne/commande` et `/borne/index` mais responsive, et sans déconnexion automatique
- Ajoute le paramètre `icon_size` dans le composant `Stars` pour controller la taille de l'icone
- Ajoute le composant `Hamburger` pour le bouton animé servant à ouvrir et fermer la sidebar
- Ajoute l'attribut `is_remote` sur les transactions, qui vaut `true` si la commande à été passé depuis un autre appareil qu'une borne
- Ajoute un favicon et des titres sur les pages "publiques"
- Redirige automatiquement vers la page d'authentification, puis vers la page de commande lors de l'authentification
- Ajoute la possibilité de masquer les commandes faites à distance sur le comptoir
- Fixe la couleur des boutons sur le popup de confirmation de la commande

Closes #86

2024-09-15 17:37 UTC, BaptTF commented on frontend/src/lib/components/client/pin.svelte
> +							console.log('f' + temp_pin)
écrit le card pin en clair

2024-09-15 17:38 UTC, BaptTF commented on frontend/src/lib/components/client/pin.svelte
> +						console.log('g' + temp_pin)
écrit le card pin en clair

2024-09-15 17:46 UTC, BaptTF requested changes
Sold out Item peuvent être cliquer ce qui fait erreur une transaction à la fin non explicite 
![image](https://github.com/user-attachments/assets/1a3941fa-273c-4f63-a07e-309808b9bd56)
![image](https://github.com/user-attachments/assets/57a88743-4404-45ba-b9ea-af068f49e1d8)
Sold out band is not on the item
![image](https://github.com/user-attachments/assets/40b69bba-96be-40db-96a5-eadbb444abd4)
Redimensionner la page /client/commande fait des erreurs JavaScript
![image](https://github.com/user-attachments/assets/99575134-5691-4668-a815-b24ffbd9664a)
Le nombre d'article dans le panier bouge selon les dimensions et n'est plus à côté du cadis vert (voir image au-dessus)
Pour voir sont panier on doit cliquer sur reste et pas sur le cadis vert ?
https://github.com/CETEN-OpenBar/bar/pull/101/files#r1760176960

2024-09-26 22:54 UTC, aripot007 commented
Normalement tout est réglé, sauf les erreurs JS qui viennent probablement de tailwind et sont pas vraiment dérangeantes (aucun effet visible sur l'interface et de toute façon ya pas grand monde qui va s'amuser à redimensionner la page)

2024-09-26 23:56 UTC, aripot007 commented
J'ai aussi ajouté un message d'erreur plus clair quand on essaie de se connecter avec un compte google qui est pas lié à un coppte bar

2024-09-29 20:19 UTC, BaptTF reviewed
Problème:
- important: pourquoi on doit scroller vers le bas pour afficher les flèches pour changer de page ?, possible de remplir en fonction de la taille de l'écran pour ne pas devoir scroller vers le bas pour avoir les flèche (à la limite si on peut changer de page en tirant sur la droite ou sur la gauche c'est moins grave)
- intermédiaire: on ne peut pas changer de page en scrollant sur la droite
- mineur: si on cliquer sur page précédente alors qu'on est sur la page 1 ce qui recharge la page 1

Version sortable comme ça mais reste des problèmes importants à corriger mais pas critique. (C'est sur qu'on va se faire critiqué sur les points ci-dessus si on la sort comme ça)

2024-09-30 10:31 UTC, aripot007 commented
Pour la page 1 qui recharge quand on va sur la page précédente, c'est un pb qui vient du système de paging et il est présent partout dans le bar, je ferai une issue pour le fix dans une autre pr.

Les deux autres problèmes sont des améliorations à faire dans le futur, je ferai une feature request pour ça.

2024-09-30 10:38 UTC, BaptTF approved these changes
lgtm !

2024-09-30 10:38 UTC, merged